export enum LobbyEventType {
  ParticipantJoined = 'participant_joined',
  ParticipantDisconnected = 'participant_disconnected',
  ParticipantReconnected = 'participant_reconnected',
  RoundArmed = 'round_armed',
  RoundReset = 'round_reset',
  Buzz = 'buzz',
  JudgedCorrect = 'judged_correct',
  JudgedIncorrect = 'judged_incorrect',
  TimeoutSet = 'timeout_set',
  TimeoutsReset = 'timeouts_reset',
  ParticipantTimeoutReset = 'participant_timeout_reset',
  ParticipantRenamed = 'participant_renamed',
  ParticipantKicked = 'participant_kicked',
  ModeChanged = 'mode_changed',
  TimeoutExpired = 'timeout_expired',
}
